### ISSUE TITLE
nad-bindings unable to find my .node file

### ISSUE THREAD

**Issue by mateodelnorte** [thlorenz/nad-bindings#2]
Hi. When I update my binding to use nad-bindings, it's unable to find my .node file as it's not looking inside node_modules/my_module_name: 

```
15:28:58.258Z ERROR node: (version=0.0.0)
    uncaughtException: Error: Could not locate the bindings file. Tried:
     → /Users/matt/development/electronifie/electronifie/fix-router/build/node_quickfix.node
     → /Users/matt/development/electronifie/electronifie/fix-router/build/Debug/node_quickfix.node
     → /Users/matt/development/electronifie/electronifie/fix-router/build/Release/node_quickfix.node
     → /Users/matt/development/electronifie/electronifie/fix-router/out/Debug/node_quickfix.node
     → /Users/matt/development/electronifie/electronifie/fix-router/Debug/node_quickfix.node
     → /Users/matt/development/electronifie/electronifie/fix-router/out/Release/node_quickfix.node
     → /Users/matt/development/electronifie/electronifie/fix-router/Release/node_quickfix.node
     → /Users/matt/development/electronifie/electronifie/fix-router/build/default/node_quickfix.node
     → /Users/matt/development/electronifie/electronifie/fix-router/compiled/0.10.36/darwin/x64/node_quickfix.node
        at bindings (/Users/matt/development/electronifie/electronifie/node-quickfix/node_modules/nad-bindings/node_modules/bindings/bindings.js:88:9)
        at resolveBinding (/Users/matt/development/electronifie/electronifie/node-quickfix/node_modules/nad-bindings/index.js:25:10)
        at Object.<anonymous> (/Users/matt/development/electronifie/electronifie/node-quickfix/index.js:2:39)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/Users/matt/development/electronifie/electronifie/fix-router/lib/fixLogonProvider.js:3:16)
```

Thanks!

**Comment by thlorenz** [comment]
should be fixed now, could you please try again?
